### ISSUE TITLE
Documentation Drive prep - Can we rename this repo happ-build-tutorial

### ISSUE THREAD

**Issue by Connoropolous** [holochain/happ-build-tutorial#13]
In my post [here](https://forum.holochain.org/t/overall-thoughts-from-developers-using-holochain/6348) I talked about the confusing-ness of languaging that gets used around app-dna-zome composability / nesting pattern, so I propose to rename this repository happ-build-tutorial since when you look at the README, the ultimate thing is a top-level h/app bundling step and commands that relate to it, so `dna` being in the name misleads it. 

By using github renaming we'll get all natural redirects so no issue there. 

This will help this repo be more naturally mentioned in a clear way from the official docs. This repository has become pretty authoritative after all.

**Comment by Connoropolous** [comment]
@guillemcordoba @zippy if there's no objection can someone with rights take that action?

**Comment by steveeJ** [comment]
Agreed and renamed :+1:

**Comment by Connoropolous** [comment]
Thanks @steveeJ !
